spring:
  application:
    name: demo-backend
  datasource:
    name: demo_mysql_db
    platform: mysql
    url: jdbc:mysql://172.17.0.2:3306/demo_backend
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTestQuery: select 1
      maximum-pool-size: 2
      connection-timeout: 60000
